### ISSUE TITLE
Pre-audit checklist

### ISSUE THREAD

**Issue by AustinGreen** [llamaxyz/llama-periphery#35]
- [x] Can remove `DuplicateSubmission` since underlying `DuplicateCast` will catch it. 
- [x] Getters for mapping in `CastData` struct.
- [x] Cast Vote and Cast Veto should check if the ActionCaster has the defined `role` still since that role can be removed and we won't know until the (Dis)approval has been submitted.
- [x] Submit Approvals and Disapprovals should also have Action State checks.
- [x] We should do vote weight adding similar to how we do `_newCastCount` in LlamaCore which has an upperbound condition.
- [x] https://github.com/llamaxyz/llama-periphery/issues/45
- [x] https://github.com/llamaxyz/llama-periphery/issues/32
- [x] Handle missing natspec and ensure existing natspec is correct. 
- [x] https://github.com/llamaxyz/llama-periphery/issues/24
- [x] https://github.com/llamaxyz/llama-periphery/issues/30
- [x] comp like token support?
- [x] Should we use uint48 for timepoint?
- [x] https://github.com/llamaxyz/llama-periphery/issues/47
- [x] LlamaTokenVotingLens contract to compute ActionCreator and Caster addresses.
- [x] https://github.com/llamaxyz/llama-periphery/issues/28
- [x] Check if terminology, function params (+ordering) and event params(+ ordering) match closely with OZ Governor. 
- [x] Change deploy function name on Factory from `deployTokenVotingModule` to `deploy`
- [x] https://github.com/llamaxyz/llama-periphery/issues/51
