### ISSUE TITLE
Post-audit checklist

### ISSUE THREAD

**Issue by AustinGreen** [llamaxyz/llama-periphery#57]
- [ ]  LlamaTokenVotingLens contract to compute LlamaTokenGovernor address.
- [x] https://github.com/llamaxyz/llama-periphery/issues/47
- [x] Handle missing natspec and ensure existing natspec is correct.
- [ ] #80
- [ ] Create llama script that creates the roles, deploys the token voting module, and assigns them. The role name can be formatted like UNI token proposer or just Token Proposer if only one governance token is expected
